name: Publicar pacote no GitHub Packages
on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  publicar:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Fazer checkout do código
        uses: actions/checkout@v5

      - name: Configurar JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'openjdk'

      - name: Configurar repositórios do Maven para o GitHub Packages da organização
        run: |
          mkdir -p ~/.m2
          echo "<settings><servers><server><id>github</id><username>${{ github.actor }}</username><password>${{ secrets.GITHUB_TOKEN }}</password></server></servers></settings>" > ~/.m2/settings.xml

      - name: Construir e empacotar com Maven
        run: mvn clean package

      - name: Publicar no GitHub Packages da Organização
        run: mvn deploy -s ~/.m2/settings.xml
